### ISSUE TITLE
Slowness in loose_bounding_box

### ISSUE THREAD

**Issue by friedmud** [libMesh/libmesh#1824]
Seeing some slowness with point locator that I think is associated with Cell::loose_bounding_box().

The offender is really `build_side_ptr()`... we really need to not call that as much as possible - the dynamic memory creation / destruction is just nasty.

![profile001](https://user-images.githubusercontent.com/870705/44295231-46049400-a262-11e8-8351-0b2b03f8353d.png)

I think the fix here for me is that there needs to be a specialization of `loose_bounding_box()` for `Hex8` that is way simpler.  We know that the sides can't be bowed out or anything - so we don't need to build them.

**Comment by friedmud** [comment]
Ok - I fixed this in #1825 by making all of the 'linear' elements use a simple method for calculating a bounding box.  Here's what this profiling looks like now:

![profile002](https://user-images.githubusercontent.com/870705/44295672-10b07400-a26b-11e8-8d4d-f1a5e350c219.png)

Somewhere in the 4x speedup or so (looking at `TrackReader::execute()` which heavily utilizes the point locator).

This will also make the point locator scale better with threads - that memory thrashing in `Cell::loose_bounding_box()` will kill threading.

**Comment by roystgnr** [comment]
Let's leave this open since it's still a problem for higher-order geometric elements?

**Comment by roystgnr** [comment]
And we can discuss possible solutions for that too.  Could you try sticking a ```has_affine_map()``` test into ```Cell::loose_bounding_box()``` and falling back to ```Elem::loose_bounding_box``` if it returns true?  That would be pretty cheap in terms of man-hours if it turns out to also save cpu-hours in the common "we have second order elements with mostly-or-all-affine maps that we use for the higher order dof storage" case.

The longer-term fixes I see may be harder.  Side has to be templated around SideType to give access to all the methods overridden by the side... but SideType is indeterminate at the Cell level, so any method there has to either itself be templated (which loose_bounding_box obviously isn't and won't be) or has to construct Side dynamically (as build_side_ptr does).

What we could do is create a new templated ```fill_side_ptr(Side<T>&)``` method that, rather than returning unique_ptr, merely reinitialiizes a provided argument.  Then in a new ```Cell::loose_bounding_box_helper<Side<T>>``` we would keep one ```Side<T>``` on the stack rather than allocating n_sides of them on the heap, and we would implement ```Hex27::loose_bounding_box()``` and so on by calling the helper method with a fixed ```Side<T>```.  That would work for everything but pyramids, which would require slightly more special code to handle the sides-of-different-types situation.

I could code that all up if it would be helpful, but I don't trust myself to properly optimize it without a test case to quantify optimizations (and/or pessimizations)...  Hand me a ```main.C``` that spends all its time in point_locator thrashing if/when you want a fix for higher-order Cells.

**Comment by jwpeterson** [comment]
> What we could do is create a new templated fill_side_ptr(Side<T>&) method that,

This method would be good to have in e.g. user code that assembles BCs, even if allocations are not as performance-sensitive in those cases.

**Comment by roystgnr** [comment]
We do have a *loose* loose_bounding_box for the biquadratic case already (albeit with a scary comment about not having a proof for the formula I overextended there...).  We could probably do the same for the triquadratic and others.  Let me know how well the has_affine_map trick works and if the answer is "not well" then we can try that next.
